### ISSUE TITLE
Chrome test runs have started failing with Chrome 54

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#142]
Getting the following error:
https://travis-ci.org/opentok/opentok-meet/jobs/168458843#L1230
```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
/home/travis/build/opentok/opentok-meet/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:365
      onError(new Error(message));
              ^
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40286
    at ClientRequest.<anonymous> (/home/travis/build/opentok/opentok-meet/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:365:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
From: Task: WebDriver.createSession()
    at acquireSession (/home/travis/build/opentok/opentok-meet/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/travis/build/opentok/opentok-meet/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Driver (/home/travis/build/opentok/opentok-meet/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at [object Object].DirectDriverProvider.getNewDriver (/home/travis/build/opentok/opentok-meet/node_modules/protractor/built/driverProviders/direct.js:69:16)
    at [object Object].Runner.createBrowser (/home/travis/build/opentok/opentok-meet/node_modules/protractor/built/runner.js:203:37)
    at /home/travis/build/opentok/opentok-meet/node_modules/protractor/built/runner.js:293:21
    at _fulfilled (/home/travis/build/opentok/opentok-meet/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/travis/build/opentok/opentok-meet/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/travis/build/opentok/opentok-meet/node_modules/q/q.js:796:13)
    at /home/travis/build/opentok/opentok-meet/node_modules/q/q.js:556:49
[launcher] Process exited with error code 1
```

**Comment by aullman** [comment]
The last pass was with Chrome 53:
https://travis-ci.org/opentok/opentok-meet/jobs/167098900

Then when Chrome 54 came out it started failing:
https://travis-ci.org/opentok/opentok-meet/jobs/167401564

**Comment by aullman** [comment]
This looks like the culprit https://bugs.chromium.org/p/chromedriver/issues/detail?id=1464

**Comment by aullman** [comment]
Fixed with https://github.com/aullman/opentok-meet/pull/143
